# Generated by Django 5.2.2 on 2025-06-12 04:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='management_level',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(validators=[accounts.validators.validate_age]),
        ),
    ]
