# Generated by Django 5.2.2 on 2025-06-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='bookings',
        ),
    ]
