# Generated by Django 5.2.3 on 2025-06-17 21:26

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[accounts.validators.validate_age]),
        ),
    ]
