# Generated by Django 5.2.2 on 2025-06-12 03:49

import accounts.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=250, unique=True)),
                ('zipcode', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_phone_number])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('branch_slug', models.SlugField(blank=True, unique=True)),
                ('branch_img', models.ImageField(blank=True, null=True, upload_to='branch_images/')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'Branches_table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_img', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('deluxe', 'Deluxe'), ('double deluxe', 'Double Deluxe'), ('suite', 'Suite')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.branch')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'Rooms_table',
                'ordering': ['branch', 'room_number'],
                'unique_together': {('branch', 'room_number', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=120)),
                ('guest_last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('id_number', models.CharField(max_length=40, unique=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='id_photos/')),
                ('check_in_date', models.DateField(verbose_name='Check-in date')),
                ('check_out_date', models.DateField(verbose_name='Check-out date')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('check_in_reminder_sent', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.branch')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.room')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'db_table': 'Bookings_table',
                'unique_together': {('guest_first_name', 'guest_last_name', 'branch', 'room', 'check_in_date')},
            },
        ),
    ]
