# Generated by Django 5.2.2 on 2025-06-12 04:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[accounts.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
