# Generated by Django 5.2.2 on 2025-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_date_of_birth_alter_booking_id_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
