# Generated by Django 5.2.2 on 2025-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
